### ISSUE TITLE
mode line is empty

### ISSUE THREAD

**Issue by commandodev** [ekaschalk/dotspacemacs#24]
My mode line is completely blank (it's there, just apparently empty). I've called `M x all-the-icons-install-fonts` but it doesn't seem to have made any different (I'm also using spacemacs-dark as my default theme).

I'm not that experienced with poking around in emacs guts, but happy to try anything to debug!

**Comment by commandodev** [comment]
Looks like I've hit this issue: https://github.com/syl20bnr/spacemacs/issues/11746

**Comment by ekaschalk** [comment]
Is it still empty or has the comment chain resolved things? I only update once every couple months so it's likely I missed being affected this.

**Comment by ekaschalk** [comment]
Hm I'm having the issue even with all of my mode-line config disabled after updating spacemacs/packages, only with `dotspacemacs-mode-line-theme   'all-the-icons`. Investigating it.

**Comment by ekaschalk** [comment]
The bug is due to `spaceline` change back in October and `spaceline-all-the-icons` was never updated, see https://github.com/domtronn/spaceline-all-the-icons.el/issues/100 for fixes. Not sure why only manifested now.

**Comment by commandodev** [comment]
Thanks @ekaschalk it's working again now.

**Comment by hexmode** [comment]
Could you please leave this bug open until this is fixed in the repository?  All we have now is a work-around.

**Comment by ekaschalk** [comment]
Yea I will keep this open for now, it's a very annoying bug and been up awhile for how trivial the fix is.

**Comment by BrandonShega** [comment]
Hi, I just came across this as well, I'm using your configuration for display packages, how would we pin the package using your method? Or does adding those lines to the `dotspacemacs/user-init` suffice?

**Comment by ekaschalk** [comment]
I'd first try the suggestion boothead posted in your `user-init`. I went into `spaceline-all-the-icons.el` and put `'` in front of the face names prefixed by `:face` in the `spaceline-compile` (except the `highlight-face` and `default-face`).

Of course this would be overwritten by updating Spacemacs, but it's easy enough and I would've expected it to be fixed by that time, but apparently it hasn't been.

**Comment by BrandonShega** [comment]
Ya, the `user-init` fix worked for me.  I have another question though, which may or may not be related to this.  If I should open a separate issue, let me know.

My mode line for helm and treemacs (all I've caught so far) is using the normal spaceline theme instead of all-the-icons and I can't figure out why.

![Treemacs](https://i.imgur.com/XRbxsQq.png)
![Helm](https://i.imgur.com/9vjt772.png)

Or maybe is the all the icons theme and just looks funny.

**Comment by ekaschalk** [comment]
Ah I've experienced this on the `messages` buffer I believe, but I don't use helm or treemacs and thought it was restricted to there. I'm not sure if it has to do with my config or it's a bug with the modeline, I'll take a look at it when I can regardless.
