### ISSUE TITLE
I added org-gcal support

### ISSUE THREAD

**Issue by commandodev** [ekaschalk/dotspacemacs#29]
Hi Eric,

I'm absolutely loving .spacemacs.d, thank you so much for sharing! I've added some stuff, most notably this morning support for `org-gcal` and syncing all my google apps calendars with my org agenda. I've also imported much of the workflow from http://doc.norang.ca/org-mode.html and have multi account support from gmail via mu4e and isync.

This has all been a lot of fun, but I've realized that I could be contributing much of this stuff back to other folks using `.spacemacs.d` if I could factor out the changes a bit better. If you're interested in having some of these changes come back upstream the comparison is here: 

https://github.com/ekaschalk/.spacemacs.d/compare/master...boothead:master

I suppose the first thing to figure out how to separate the changes that are specific to me in `config/layers.el` and `config/packages.el`. Perhaps the personal layer could be a place for that?

Any thoughts?

**Comment by ekaschalk** [comment]
I'll consider changes but it might be more appropriate to submit to Spacemacs rather than here. I'm not sure I see this repo as a personal-turned-community-config ala doom-emacs. Spacemacs is already that after all. I'm undecided on whether to include configuration I personally don't use into here, I have to think about that. 

As to how, separate your modifications into their own init blocks. They can then be included wherever, making your own layer only if you want to expose options for how those init blocks run and set stuff.
