### ISSUE TITLE
Error when starting up

### ISSUE THREAD

**Issue by sigu** [ekaschalk/dotspacemacs#6]
Thanks so much for this, really helpful. I am using it though I dont understand the configurations much hence it is hard to troubleshoot some issues. Currently when I start up it displays the following error
`Error (use-package): org-projectile :config: Symbol’s function definition is void: org-projectile:per-repo`

**Comment by ekaschalk** [comment]
This is likely due to some recent updates in an org related package. Try going through each require in `config/local/org-config` and search for any use of `org-projectile:per-repo`. First see if disabling the `org-config` layer is enough to fix the problem, by just commenting it out in `config/packages`.

**Comment by sigu** [comment]
THere is not use of `org-projectile:per-repo` in the `config/local/org-config`, I went ahead and commented out `org-config` layer in the `config/packages`

What will I miss by commenting this out 🤔 ?

**Comment by ekaschalk** [comment]
The nice part about this style of config is it makes bisecting very easy.
When you have one large config file there are usually interdepencies scattered throughout.
But here you can comment out one layer/one package and not mess up the rest.

Comment out the personal layers (except macros layers) to see which one causes the issue.
Then comment out the packages in the `packages.el` of that layer until you find which one.

**Comment by sigu** [comment]
Thanks, this worked 🎉 🎉
