### ISSUE TITLE
How to use your display packages in spacemacs

### ISSUE THREAD

**Issue by beyondpie** [ekaschalk/dotspacemacs#7]
Hi, 
I see your blog, and the displays are really amazing.
I want to use it as my private layer. But I see there are some variables depend on other layers in your spacemacs.d, is that possible that I only use your display package, while keep my settings for other things?
BTW, I use macOS.
Thanks a lot!
Songpeng

**Comment by georgreen** [comment]
Hey did you figure this out? I'm a trying to figure out how to use this but it proving to be quiet a challenge. Would you mind pointing me in the right direction?

**Comment by ekaschalk** [comment]
Each package in the display layer (its local dir) is setup by `display/packages.el`'s `display/init-pkg-name` functions. They are are all self-contained and separate*.

So installing a pkg is as simple as appending the body of that function into the pkg.el, putting it on your load/path or in your init.el, and running it.

It's ordered this way so my personal settings for each pkg aren't hardcoded into the pkgs themselves. So feel free to mess with any of the contents in the `display/init-pkg-name` funcs.


* Except for the char <-> unicode points set by `pretty-fonts` which other packages assume are set (otherwise you will see weird chars all-over).

**Comment by georgreen** [comment]
After hours of trying, I figured it out, copy all the folders from this repo within `layers` folder to `.emacs.d/private/` then add `display` into your `.spacemacs` config file in this section `dotspacemacs-configuration-layers`. @songpeng @ekaschalk Is it possible to just get the mathematics notation only without the other changes? I will appreciate this.:grinning:
